<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Academic Regulations</name>
   <tag></tag>
   <elementGuidId>da8c1e3d-d49f-4a25-b454-c2f732204ee8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ul2']/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Academic Regulations&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3caf8fbe-4702-4525-83b2-6d46f1a92353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Academic Regulations</value>
      <webElementGuid>db5430ae-92dc-4c73-9d42-4ae0b4aa8bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>e90477d5-66cd-4558-9548-3284e2a2dcb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://vit.ac.in/sites/default/files/academic/Academic-Regulations.pdf</value>
      <webElementGuid>64dfd6b2-af3e-4b7a-9f6d-03817a05f52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Academic Regulations</value>
      <webElementGuid>96fb039a-61a3-46b6-99c0-060ccc839ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ul2&quot;)/li[@class=&quot;vc-menu-item&quot;]/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>8a2c60b2-876a-46e3-9a5b-7ac203d1eb3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ul2']/li[2]/a</value>
      <webElementGuid>de338170-8e6f-47f8-9082-2804028477ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Academic Regulations')]</value>
      <webElementGuid>da3c2e4d-a0e9-4fb8-9981-545d5c0f2929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[2]/following::a[1]</value>
      <webElementGuid>8d1628c8-90a0-4909-ac5e-1c3a33a2e841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Academics'])[2]/following::a[3]</value>
      <webElementGuid>9763be2f-7eb6-4cac-bb93-32de7c43ac59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Academic Council'])[1]/preceding::a[1]</value>
      <webElementGuid>64c9dd18-1c97-4c47-a38f-309488f42c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Curriculum'])[1]/preceding::a[2]</value>
      <webElementGuid>b698e77a-8ddf-4ec8-b02d-facabdbd1299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Academic Regulations']/parent::*</value>
      <webElementGuid>709ad170-243d-46e7-96b4-10220a279dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://vit.ac.in/sites/default/files/academic/Academic-Regulations.pdf')]</value>
      <webElementGuid>5989022a-c6f4-4d63-91c9-41c14c37228d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/ul/li[2]/a</value>
      <webElementGuid>ea12e46e-0e23-4c51-8b8a-cd2e97670095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Academic Regulations' and @href = 'https://vit.ac.in/sites/default/files/academic/Academic-Regulations.pdf' and (text() = 'Academic Regulations' or . = 'Academic Regulations')]</value>
      <webElementGuid>a76c5995-a439-4248-ac3b-ac0e18fbeba1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
