<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Postgraduate</name>
   <tag></tag>
   <elementGuidId>d294ca52-4205-4a38-8119-dcf3db8b9042</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ul3']/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Postgraduate&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ea6ebea5-552a-46c9-a9dc-bebe44bd99d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Postgraduate</value>
      <webElementGuid>d323ac8e-7902-452a-a71c-af7be25cbb04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>a24dc56d-57a5-4a39-bbde-08487306a9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://vit.ac.in/all-courses/pg</value>
      <webElementGuid>e7a09f7c-a2a1-415e-8087-0220acb294c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Postgraduate</value>
      <webElementGuid>be5c2a2a-08a6-49dc-967c-afd15617daa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ul3&quot;)/li[@class=&quot;vc-menu-item&quot;]/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>bcab1bb5-5891-436a-815c-19c67c5fde6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ul3']/li[4]/a</value>
      <webElementGuid>c59fba5d-f63c-43bf-9d9d-241af9fc9e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Postgraduate')]</value>
      <webElementGuid>257c48b6-ba57-479a-965e-6cb16a4b89d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Undergraduate'])[1]/following::a[1]</value>
      <webElementGuid>410f0855-392c-43aa-bc2f-b08b16bcd1c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Programmes Offered'])[1]/following::a[2]</value>
      <webElementGuid>b03dcea2-8d94-4560-b335-205650ba9036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Research'])[1]/preceding::a[1]</value>
      <webElementGuid>a45dca41-7b7f-4537-93c6-8e6de24e49dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='International'])[1]/preceding::a[2]</value>
      <webElementGuid>141f6619-88b0-4b20-b361-a44a56b62650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Postgraduate']/parent::*</value>
      <webElementGuid>c785271b-53cc-4323-8ed6-15abbebbd80c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://vit.ac.in/all-courses/pg')]</value>
      <webElementGuid>a04b07a5-802e-4878-b17e-fdd7d88b55ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/ul/li[4]/a</value>
      <webElementGuid>a3105a02-dc06-4212-a17d-56b5893201e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Postgraduate' and @href = 'https://vit.ac.in/all-courses/pg' and (text() = 'Postgraduate' or . = 'Postgraduate')]</value>
      <webElementGuid>cf4ff69e-4578-4995-b11a-52ce6ab0ff76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
