<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Electrical and Electronics Engineering</name>
   <tag></tag>
   <elementGuidId>1ec9039b-f35f-468e-a368-eca0997a309c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarNavDropdown']/ul/li[4]/ul/li/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Electrical and Electronics Engineering&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8dfdc53c-2854-42f7-a27f-1148bd97b0d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.annauniv.edu/EEE</value>
      <webElementGuid>5b8472a7-e870-4c07-a6ce-598cd0ab7241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>6f53f594-db73-4815-958e-e2afaff3ee17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Electrical and Electronics Engineering</value>
      <webElementGuid>b80e5e45-e02f-4215-a572-78b42f829950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarNavDropdown&quot;)/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;has-mega-menu&quot;]/ul[@class=&quot;mega-menu&quot;]/li[1]/ul[1]/li[4]/a[1]</value>
      <webElementGuid>c5934515-c791-4f28-a4a6-9b3383631431</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarNavDropdown']/ul/li[4]/ul/li/ul/li[4]/a</value>
      <webElementGuid>b6c9690e-67b4-471c-95d4-5fcd0126fad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Electrical and Electronics Engineering')]</value>
      <webElementGuid>64ecaf32-fcc9-4307-9693-99189587ece6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Computer Science and Engineering'])[1]/following::a[1]</value>
      <webElementGuid>bfdf190a-5e9e-43cf-8644-dbcaaf7fe2f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chemistry'])[1]/following::a[2]</value>
      <webElementGuid>10cc36c3-381a-462b-b93a-48023936834e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Electronics and Communication Engineering'])[1]/preceding::a[1]</value>
      <webElementGuid>2a2268f7-45b0-40f3-a470-943bb3273b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/preceding::a[2]</value>
      <webElementGuid>b6d044f1-23ff-41a3-9dd4-b6c8c4b28bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Electrical and Electronics Engineering']/parent::*</value>
      <webElementGuid>572d27dc-bea8-4344-aabf-43dfa9ff4fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.annauniv.edu/EEE')]</value>
      <webElementGuid>908b7cd7-610d-4fea-a197-9bdb7271e7bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li/ul/li[4]/a</value>
      <webElementGuid>e01926f6-8dc9-4c21-9703-3aaa16d700d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.annauniv.edu/EEE' and (text() = 'Electrical and Electronics Engineering' or . = 'Electrical and Electronics Engineering')]</value>
      <webElementGuid>a55f4ccd-8a58-480b-906b-955fe47d0364</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
