<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Departments</name>
   <tag></tag>
   <elementGuidId>86de1886-d5a3-4766-91ce-bcd8158626cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Departments')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Departments&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b3bfd13b-75b7-4fa8-8857-2e82c49e6bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>24fabb2d-9209-46cf-98f6-ec17dfd630fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Departments</value>
      <webElementGuid>9f71c0b3-7261-425b-9aee-c0507557e0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js&quot;]/body[@class=&quot;path-node node--type-page page__loader&quot;]/div[@class=&quot;dialog-off-canvas-main-canvas&quot;]/header[@class=&quot;header&quot;]/div[@class=&quot;header__bottomsec&quot;]/div[@class=&quot;container&quot;]/nav[@class=&quot;navigation__slideShow active&quot;]/ul[@class=&quot;navigation__menu&quot;]/li[@class=&quot;navigation__submenudropdown active&quot;]/ul[@class=&quot;navigation__submenu&quot;]/li[@class=&quot;navigation__innersubmenu&quot;]/a[1]</value>
      <webElementGuid>8c83ea1d-2aac-4810-87a5-f110c9f2fe58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Departments')]</value>
      <webElementGuid>a4b2d9b8-5055-4cd2-be23-b2ae9d5f7309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exchange Programmes'])[1]/following::a[1]</value>
      <webElementGuid>8b0e50c2-258f-42ee-900e-863d6a1d3c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Joint Degree Programmes'])[1]/following::a[2]</value>
      <webElementGuid>145bafec-2dbd-475f-b195-dfb276cafa34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aerospace Engineering'])[1]/preceding::a[1]</value>
      <webElementGuid>dbcfcc22-e321-4306-a07b-58a5125df321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applied Mechanics &amp; Biomedical Engineering'])[1]/preceding::a[2]</value>
      <webElementGuid>262f98c1-babb-4277-90d5-7c14ca099385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Departments']/parent::*</value>
      <webElementGuid>fec08dd9-a8a9-4d6b-8b55-8708fd3b27c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[9]</value>
      <webElementGuid>ec205e41-7939-4d4a-8238-3fac60c3bddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[3]/a</value>
      <webElementGuid>77142aea-ede1-42d2-8279-5ced87198838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Departments' or . = 'Departments')]</value>
      <webElementGuid>b3f0b656-ee0d-4beb-9ce9-167c26f84dba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
