<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Menu</name>
   <tag></tag>
   <elementGuidId>43adae7a-be93-4ab8-9cc4-b4501da370ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.vc-mm-mobile-toggle-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fontSize']/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Menu &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>88ee624c-b15c-45f4-abd4-d9163085d2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>42e6b4cd-0a5a-46b3-ba49-bcfd08c81f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link vc-mm-mobile-toggle-btn</value>
      <webElementGuid>019e3d63-e749-427d-bb40-ec510e17cf91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Menu </value>
      <webElementGuid>c7abcd68-078f-4094-91f7-ab23e9872bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stick&quot;)/div[@class=&quot;menu_pos&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;bck_menu&quot;]/div[@class=&quot;col-md-10 col-sm-10 col-xs-12 menu_mobile&quot;]/div[@id=&quot;fontSize&quot;]/ul[@class=&quot;vc-nav-on-mobile vc-mm-menu&quot;]/li[@class=&quot;vc-menu-item vc-mm-mobile-toggle&quot;]/a[@class=&quot;nav-link vc-mm-mobile-toggle-btn&quot;]</value>
      <webElementGuid>0728fa61-6775-457c-b3c0-277b67c5d2d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fontSize']/ul/li/a</value>
      <webElementGuid>68e63ca9-2f23-4cc0-bb3c-f8bc43d07484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Menu')]</value>
      <webElementGuid>21db79ff-6389-4741-9651-c59dd0605532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIT - Bangalore'])[1]/following::a[2]</value>
      <webElementGuid>1c8ee0a4-86a3-45ab-ba6a-608679871fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIT - BHOPAL'])[1]/following::a[3]</value>
      <webElementGuid>c55a9435-fce0-4029-bd29-8d1071992b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIT'])[1]/preceding::a[2]</value>
      <webElementGuid>2466f113-f3e2-4f1e-8d94-f377959bcea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::a[3]</value>
      <webElementGuid>7330016a-4bb0-4d4a-924c-345de69569f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Menu']/parent::*</value>
      <webElementGuid>9f8337be-419b-467c-bfff-d44158890d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>4d800f31-9269-4ed1-8f1d-62daa3314e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>6da064fb-2f43-4379-bb55-e2fb498dc61b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = ' Menu ' or . = ' Menu ')]</value>
      <webElementGuid>61b25e71-2a54-488d-915e-ccb8f22e9973</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
