<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_PROGRAMMES OFFERED</name>
   <tag></tag>
   <elementGuidId>b9a823a7-cff5-42ab-bd5e-c66d450d578b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.title4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block-system-main']/div/div/div/section/div/div/div/div/div/div/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;PROGRAMMES OFFERED&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>14195103-b8f1-424d-b4fa-bf95e4081678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title4</value>
      <webElementGuid>43e60242-16a7-40e1-82db-7e981348a371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PROGRAMMES OFFERED</value>
      <webElementGuid>d3e13035-30e8-4b39-b9cf-dccb5af082cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-system-main&quot;)/div[@class=&quot;content&quot;]/div[@class=&quot;view view-admissions-research view-id-admissions_research view-display-id-page view-dom-id-06b0792e55e4c15cbb9736900696b1cc&quot;]/div[@class=&quot;view-content&quot;]/section[@class=&quot;section inner_rg_section&quot;]/div[@class=&quot;common_row_30 section&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row_mar_minus clearfix&quot;]/div[@class=&quot;col-md-9 col-6-sm col-xs-12&quot;]/div[@class=&quot;sccodian_closeAble course_acc smk_accordion acc_with_icon&quot;]/div[@class=&quot;accordion_in&quot;]/div[@class=&quot;acc_head&quot;]/h3[@class=&quot;title4&quot;]</value>
      <webElementGuid>18eab1a0-c6c1-4316-a72b-9293fab2b1c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-system-main']/div/div/div/section/div/div/div/div/div/div/div/h3</value>
      <webElementGuid>0831c757-b85c-4ce3-8b52-d8048f04d464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Research Guide Selection Portal for VITREE - 2024 January session'])[1]/following::h3[1]</value>
      <webElementGuid>c63705ab-270d-4b94-b7ed-7550e450c3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Research Guide Directory (Schools / Centres – 2024, Vellore Campus)'])[1]/following::h3[1]</value>
      <webElementGuid>b5d447ee-8bba-42ca-89f2-8d5fcb5e7f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESEARCH PROGRAMMES OFFERED IN VIT AT VARIOUS CAMPUSES &amp; SCHOOLS'])[1]/preceding::h3[1]</value>
      <webElementGuid>7f2309e1-4d6f-4dee-b380-2527e3d27d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To know more details'])[1]/preceding::h3[1]</value>
      <webElementGuid>0f1e4836-be39-4ec6-970e-199885848ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PROGRAMMES OFFERED']/parent::*</value>
      <webElementGuid>d2f92ddb-05b2-4858-9f91-26bf6f2055d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/h3</value>
      <webElementGuid>15086999-4a99-43bc-a1e2-e906dfedfac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'PROGRAMMES OFFERED' or . = 'PROGRAMMES OFFERED')]</value>
      <webElementGuid>ed25c200-7bc4-442c-98ec-b28a98e3f915</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
