<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Academic Schedule</name>
   <tag></tag>
   <elementGuidId>fd707670-2099-4d3b-b458-02b2e2457895</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.academicschedule</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='navbar']/ul/li[2]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Academic Schedule&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>94a13a05-af51-469c-8040-5ebdfa97146c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>academicschedule</value>
      <webElementGuid>20b82749-65df-4237-a437-0df3345bf478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.auegov.ac.in/Department/ct/academicschedule</value>
      <webElementGuid>2778dc82-8e23-4538-ba5a-a758256406f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Academic Schedule</value>
      <webElementGuid>0d3a5252-ac22-42af-b59a-363a928e3590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar&quot;)/ul[1]/li[@class=&quot;dropdown&quot;]/ul[1]/li[2]/a[@class=&quot;academicschedule&quot;]</value>
      <webElementGuid>c207ef5e-2900-4546-8be4-589c2dcf14ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbar']/ul/li[2]/ul/li[2]/a</value>
      <webElementGuid>95c46334-66f3-4e2a-8e54-5c71c22b135b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Academic Schedule')]</value>
      <webElementGuid>4778a412-3e76-4698-b068-66a2f2e8d2b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Courses Offered'])[1]/following::a[1]</value>
      <webElementGuid>66d6f4b0-147c-4803-8e49-b6ce7b19df77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Academic'])[1]/following::a[2]</value>
      <webElementGuid>7a49cc6e-368e-46c5-b044-b39d54a2712b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='People'])[1]/preceding::a[1]</value>
      <webElementGuid>45f59a00-488d-4c85-a70f-ed006aef15fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teaching'])[1]/preceding::a[2]</value>
      <webElementGuid>86f40814-621b-4a39-baeb-302e3cc84699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Academic Schedule']/parent::*</value>
      <webElementGuid>a32832f7-6dc5-49e1-b6b3-ec8d879aeb93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.auegov.ac.in/Department/ct/academicschedule')]</value>
      <webElementGuid>a6d5c17b-b2d7-4cd7-842d-3f210ae0a3e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[2]/a</value>
      <webElementGuid>5cf34dd4-44a9-41da-acc2-68d0ec59221b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.auegov.ac.in/Department/ct/academicschedule' and (text() = 'Academic Schedule' or . = 'Academic Schedule')]</value>
      <webElementGuid>cee0d68b-df34-4517-a508-8109ad041d02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
